version: "3.8"

services:
  api:
    build: .
    container_name: face-recognition-api
    ports:
      - "8000:8000"
    volumes:
      - ./Dataset:/app/Dataset
      - ./Models:/app/Models
      - ./api/.env:/app/api/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
